[package]
name = "mchprs_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bitbuffer"
harness = false

[[bench]]
name = "chungus"
harness = false

[dependencies]
mchprs_proc_macros = { path = "../proc_macros" }
toml = "0.5"
byteorder = "1.4"
hematite-nbt = "0.5"
bitflags = "1.2"
serde = "1"
serde_json = "1.0"
md5 = "0.7"
bus = "2.2"
ctrlc = { version = "3.1", features = ["termination"] }
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4"
rand = "0.8"
regex = { version = "1.4" }
backtrace = "0.3"
rusqlite = { version="0.27", features=["bundled"] }
anyhow = "1.0"
rayon = "1.5"
cranelift = { version = "0.77", optional = true }
cranelift-jit  = { version = "0.77", optional = true }
cranelift-module  = { version = "0.77", optional = true }
toml_edit = "0.14"
mysql = "22"
tokio = { version = "1", features = ["rt-multi-thread"] }
reqwest = { version = "0.11", features = ["json"] }
itertools = "0.10"
impls = "1"
bincode = "1.3"
once_cell = "1.14.0"
redpiler_graph = { path = "../redpiler_graph" }
mchprs_save_data = { path = "../save_data" }
mchprs_blocks = { path = "../blocks" }
mchprs_world = { path = "../world" }
mchprs_utils = { path = "../utils" }
mchprs_network = { path = "../network" }

[features]
jit_cranelift = ["cranelift", "cranelift-jit", "cranelift-module"]
